






































"""
Phase 9 -- Full-Dataset Undertone Descriptor (batch run)

Computes the Majority Undertone Label (and the 5 per-region hue angles and
labels that feed it) across the full landmarked dataset, using the real
masks in label_maps/.

CIELAB SOURCE -- follows the manuscript:
    Stage 6 "utilizes the CIELAB Feature Vector produced in Stage 5", and
    Stage 5 converts "the per-region skin samples produced by the SSR stage".
    So the undertone is computed from the SSR image (CIELAB_SOURCE = "ssr").

    An earlier version used the original (pre-SSR) crop instead, based on the
    Phase 8.2 source comparison (qa_cielab_source_compare.py) run when SSR
    used sigma = 80, which flattened a*/b*. SSR now uses sigma = 30.
    CIELAB_SOURCE = "original" is kept as a DIAGNOSTIC only: it writes to a
    separate CSV so the two can be compared for the adviser, and it must not
    be reported as HueView's undertone unless the manuscript's Stage 5/6 are
    changed to say so.

Only the full_face configuration is processed per image -- it already
contains all 5 individual regions' hue/label as part of its own computation,
so separately running the 5 single-region configs would just recompute
numerically identical hue values from the same underlying patches. Regions
with no usable skin pixels are excluded from the vote (undertone.py).

This is the actual data behind the manuscript's Appendix 5 ("Undertone
outputs generated by HueView... are reported descriptively in Appendix 5
only") -- not a QA sample.

Input:
    data/processed/landmarks_index.csv
    data/processed/label_maps/<filename, .png>        -- from 7.4
    data/processed/images_ssr/<filename>               -- from 7.2 (sigma = 30)
    (original pre-SSR crop via path_resolver -- diagnostic mode only)

HUE THRESHOLD (being tried, not in the manuscript yet):
    `majority_undertone` uses the DATASET-RELATIVE centre: the train-split
    median region hue, STW_TRAIN_CENTRE_DEG = 42.4 deg (undertone.py, from
    phase9_threshold_preview.py), with the researchers' +/- 5 deg band:
        Warm > 47.4,  Neutral 37.4-47.4,  Cool < 37.4
    The manuscript rule (60 +/- 5, Pantone / Sirisayan) is kept alongside as
    `majority_undertone_60` for Appendix 5.

CHROMA FLOOR COMPARISON (proposed, not in the manuscript yet): Alongside it, the same images are re-voted with
    each floor in CHROMA_FLOORS: regions with C*ab below the floor are
    "Indeterminate" and do not vote (undertone.py, decision (d)). Nothing is
    changed in the reported result until the team/adviser pick a floor.

Output:
    data/processed/phase9_undertone.csv -- one row per image:
        filename, split, scc_label,
        <region>_L, _a, _b, _chroma, _hue_deg, _undertone (x5, 42.4 deg rule),
        majority_undertone, was_tied, n_regions_present   (42.4 deg rule)
        majority_undertone_60, was_tied_60                (manuscript 60 deg rule)
        majority_undertone_c<F>, n_regions_voted_c<F>     (42.4 deg + chroma floor F)
        (n_regions_present = regions that were actually measured and voted)
    data/processed/phase9_chroma_floor_comparison.csv -- label % per SCC per rule
    data/processed/phase9_failures.csv  -- filename, reason (only if any)
    Diagnostic mode writes phase9_undertone_original_diagnostic.csv /
    phase9_failures_original_diagnostic.csv instead.
"""

# BLAS thread-limiting before numpy/skimage/cv2 import anywhere -- same fix
# as qa_cielab_source_compare.py; build_cielab_vector's skimage.color.rgb2lab
# call is BLAS-backed, and 12 worker processes each doing that repeatedly
# causes OpenBLAS thread oversubscription without this.
import os

os.environ.setdefault("OMP_NUM_THREADS", "1")
os.environ.setdefault("OPENBLAS_NUM_THREADS", "1")
os.environ.setdefault("MKL_NUM_THREADS", "1")
os.environ.setdefault("NUMEXPR_NUM_THREADS", "1")
os.environ.setdefault("VECLIB_MAXIMUM_THREADS", "1")

import sys
from pathlib import Path
from multiprocessing import Pool, cpu_count

import cv2
import numpy as np
import pandas as pd
from tqdm import tqdm

# ------------------------------------------------------------ project root --


def find_project_root(start: Path, marker: str = "data") -> Path:
    for candidate in [start] + list(start.parents):
        if (candidate / marker).is_dir():
            return candidate
    return start


PROJECT_ROOT = find_project_root(Path(__file__).resolve().parent)
sys.path.insert(0, str(PROJECT_ROOT / "src"))

from ml_pipeline.src.baseline.path_resolver import resolve_image_path  # noqa: E402
from ml_pipeline.src.hueview.regions import decode_label_map, REGION_ORDER  # noqa: E402
from ml_pipeline.src.hueview.region_selector import RegionalConfigurationSelector, FULL_FACE  # noqa: E402
from ml_pipeline.src.hueview.cielab_features import build_cielab_vector  # noqa: E402
from ml_pipeline.src.hueview.undertone import (  # noqa: E402
    HALF_BAND_DEG, INDETERMINATE, PROPOSED_CHROMA_FLOOR, REFERENCE_ANGLE_DEG,
    STW_TRAIN_CENTRE_DEG, compute_undertone_descriptor, majority_with_chroma_floor)

# ---------------------------------------------------------------- config --

INDEX_PATH = PROJECT_ROOT / "data" / "processed" / "landmarks_index.csv"
LABEL_MAPS_ROOT = PROJECT_ROOT / "data" / "processed" / "label_maps"
SSR_ROOT = PROJECT_ROOT / "data" / "processed" / "images_ssr"
OUT_PATH = PROJECT_ROOT / "data" / "processed" / "phase9_undertone.csv"
FAILURES_PATH = PROJECT_ROOT / "data" / "processed" / "phase9_failures.csv"
COMPARISON_PATH = PROJECT_ROOT / "data" / "processed" / "phase9_chroma_floor_comparison.csv"
SPLITS = ("train", "val", "test")

# Hue thresholds: dataset-relative centre (reported) and manuscript 60 deg (comparison)
HUE_CENTRE_DEG = STW_TRAIN_CENTRE_DEG      # 42.4
HALF_BAND = HALF_BAND_DEG                  # 5
CENTRES_PATH = PROJECT_ROOT / "data" / "processed" / "phase9_threshold_centres.csv"

# Chroma floors to compare (C*ab). 13 = proposed (2.3 JND / tan 10 deg).
CHROMA_FLOORS = (10, round(PROPOSED_CHROMA_FLOOR), 20)
LABEL_ORDER = ("Cool", "Neutral", "Warm", INDETERMINATE)

LIMIT = None  # e.g. 50 to sanity-check before the full run

# "ssr"      -- manuscript (Stage 6 -> Stage 5 -> SSR image). Use this.
# "original" -- pre-SSR colour, DIAGNOSTIC only, written to separate files.
CIELAB_SOURCE = "ssr"

if CIELAB_SOURCE not in ("ssr", "original"):
    raise SystemExit(f"CIELAB_SOURCE must be 'ssr' or 'original', got {CIELAB_SOURCE!r}")
if CIELAB_SOURCE == "original":
    OUT_PATH = OUT_PATH.with_name("phase9_undertone_original_diagnostic.csv")
    FAILURES_PATH = FAILURES_PATH.with_name("phase9_failures_original_diagnostic.csv")
    COMPARISON_PATH = COMPARISON_PATH.with_name("phase9_chroma_floor_comparison_original_diagnostic.csv")

# --------------------------------------------------------------- worker --


def process_one(filename: str):
    label_path = LABEL_MAPS_ROOT / Path(filename).with_suffix(".png")
    ssr_path = SSR_ROOT / filename

    label = cv2.imread(str(label_path), cv2.IMREAD_UNCHANGED)
    ssr_bgr = cv2.imread(str(ssr_path))
    if label is None or ssr_bgr is None:
        return (filename, None, "label_map_or_ssr_missing")

    ssr_rgb = cv2.cvtColor(ssr_bgr, cv2.COLOR_BGR2RGB)
    patches = decode_label_map(label, ssr_rgb)

    # The original (pre-SSR) crop is only needed for the diagnostic mode.
    orig_rgb = None
    if CIELAB_SOURCE == "original":
        orig_path, _, _ = resolve_image_path(filename)
        if orig_path is None:
            return (filename, None, "original_not_found")
        orig_bgr = cv2.imread(str(orig_path))
        if orig_bgr is None:
            return (filename, None, "original_unreadable")
        orig_rgb = cv2.cvtColor(orig_bgr, cv2.COLOR_BGR2RGB)

    selector = RegionalConfigurationSelector(configurations=(FULL_FACE,))
    outputs = list(selector.route(patches, image_id=filename))
    if not outputs:
        return (filename, None, "full_face_unusable")

    cfg = outputs[0]
    cielab_vec = build_cielab_vector(cfg, original_rgb=orig_rgb)
    result = compute_undertone_descriptor(cfg, cielab_vec,
                                          center=HUE_CENTRE_DEG, half_band=HALF_BAND)
    if result is None:
        # No region had usable skin pixels -- nothing was measured.
        return (filename, None, "no_measured_regions")

    row = {"filename": filename}
    for name in REGION_ORDER:
        info = result["regions"].get(name)
        for key in ("L", "a", "b", "chroma", "hue_deg"):
            row[f"{name}_{key}"] = round(info[key], 2) if info else None
        row[f"{name}_undertone"] = info["undertone"] if info else None
    # Dataset-relative rule (reported result)
    row["majority_undertone"] = result["majority_undertone"]
    row["was_tied"] = result["was_tied"]
    row["n_regions_present"] = result["n_regions_voted"]  # measured regions only
    # Manuscript 60 deg rule (comparison, Appendix 5)
    label60, tied60, _ = majority_with_chroma_floor(result["regions"], None,
                                                    REFERENCE_ANGLE_DEG, HALF_BAND)
    row["majority_undertone_60"] = label60
    row["was_tied_60"] = tied60
    # Proposed chroma floors on top of the dataset-relative rule (comparison only)
    for floor in CHROMA_FLOORS:
        label, _, n_voted = majority_with_chroma_floor(result["regions"], floor,
                                                       HUE_CENTRE_DEG, HALF_BAND)
        row[f"majority_undertone_c{floor}"] = label
        row[f"n_regions_voted_c{floor}"] = n_voted

    return (filename, row, None)


# --------------------------------------------------------------- main --


def load_scc_labels() -> pd.DataFrame:
    """filename -> split, scc_label from train/val/test.csv (for the report only)."""
    frames = []
    for split in SPLITS:
        path = PROJECT_ROOT / "data" / "processed" / f"{split}.csv"
        if not path.is_file():
            print(f"  (no {path.name} -- SCC breakdown will skip it)")
            continue
        df = pd.read_csv(path)
        col = next((c for c in df.columns if c.lower() in ("scc_label", "scc")), None)
        if col is None:
            continue
        frames.append(pd.DataFrame({"filename": df["filename"].astype(str),
                                    "split": split, "scc_label": df[col].astype(str)}))
    if not frames:
        return pd.DataFrame(columns=["filename", "split", "scc_label"])
    return pd.concat(frames).drop_duplicates("filename")


def pct_table(df: pd.DataFrame, col: str) -> pd.DataFrame:
    """% of each label per SCC (rows) + an ALL row."""
    t = pd.crosstab(df["scc_label"], df[col], normalize="index") * 100
    t.loc["ALL"] = df[col].value_counts(normalize=True) * 100
    return t.reindex(columns=[c for c in LABEL_ORDER if c in t.columns]).fillna(0).round(1)


def print_comparison(df: pd.DataFrame):
    chroma_cols = [f"{r}_chroma" for r in REGION_ORDER]
    print("\nREGION CHROMA C*ab (measured regions)")
    print("-" * 60)
    by_scc = df.groupby("scc_label")[chroma_cols].median()
    by_scc.columns = [r for r in REGION_ORDER]
    print("median per SCC:")
    print(by_scc.round(1).to_string())

    all_c = df[chroma_cols].stack()
    print("\n% of measured regions BELOW each floor (all images):")
    print("  " + "   ".join(f"C*<{f}: {100 * (all_c < f).mean():.1f}%" for f in CHROMA_FLOORS))

    rows = []
    rules = [(f"centre {HUE_CENTRE_DEG} (reported)", "majority_undertone"),
             (f"manuscript {REFERENCE_ANGLE_DEG:g}", "majority_undertone_60")] + \
            [(f"centre {HUE_CENTRE_DEG} + C*>={f}", f"majority_undertone_c{f}")
             for f in CHROMA_FLOORS]
    for name, col in rules:
        t = pct_table(df, col)
        print(f"\nMAJORITY UNDERTONE % BY SCC -- {name}")
        print("-" * 60)
        print(t.to_string())
        long = t.reset_index().melt(id_vars="scc_label", var_name="undertone", value_name="percent")
        long.insert(0, "rule", name)
        rows.append(long)
    pd.concat(rows).to_csv(COMPARISON_PATH, index=False)
    print(f"\nSaved {COMPARISON_PATH}")



def check_centre():
    """Warn if the preview's train median no longer matches the constant used."""
    if not CENTRES_PATH.is_file():
        return
    c = pd.read_csv(CENTRES_PATH)
    g = c.loc[c["rule"] == "global", "centre_deg"]
    if len(g) and abs(float(g.iloc[0]) - HUE_CENTRE_DEG) > 0.05:
        print(f"WARNING: {CENTRES_PATH.name} says the train median is {float(g.iloc[0])} deg, "
              f"but STW_TRAIN_CENTRE_DEG = {HUE_CENTRE_DEG}. Update undertone.py if the "
              f"pipeline changed.")


def run():
    print(f"Project root: {PROJECT_ROOT}")
    print(f"Hue rule: Warm > {HUE_CENTRE_DEG + HALF_BAND:.1f}, "
          f"Neutral {HUE_CENTRE_DEG - HALF_BAND:.1f}-{HUE_CENTRE_DEG + HALF_BAND:.1f}, "
          f"Cool < {HUE_CENTRE_DEG - HALF_BAND:.1f}  (centre = train median; "
          f"manuscript 60 deg kept as majority_undertone_60)")
    check_centre()
    print(f"CIELAB source: {CIELAB_SOURCE}"
          + ("  (manuscript)" if CIELAB_SOURCE == "ssr" else "  (DIAGNOSTIC -- not the reported result)"))

    if not INDEX_PATH.is_file():
        raise SystemExit(f"ERROR: {INDEX_PATH} not found.")

    index_df = pd.read_csv(INDEX_PATH)
    filenames = index_df["filename"].tolist()
    print(f"{INDEX_PATH.name}: {len(filenames)} images")

    if LIMIT:
        filenames = filenames[:LIMIT]
        print(f"LIMIT set -- only processing {len(filenames)} images")

    print(f"Total: {len(filenames)} images, {cpu_count()} workers")

    rows = []
    failures = []

    with Pool(processes=cpu_count()) as pool:
        for filename, row, error in tqdm(pool.imap_unordered(process_one, filenames), total=len(filenames)):
            if error is not None:
                failures.append({"filename": filename, "reason": error})
            else:
                rows.append(row)

    df = pd.DataFrame(rows)
    if rows:
        df = load_scc_labels().merge(df, on="filename", how="right")
        front = ["filename", "split", "scc_label"]
        df = df[front + [c for c in df.columns if c not in front]].sort_values("filename")
        df["scc_label"] = df["scc_label"].fillna("unknown")
    df.to_csv(OUT_PATH, index=False)

    print(f"\nProcessed {len(rows)} / {len(filenames)} images successfully")
    if failures:
        fail_df = pd.DataFrame(failures)
        fail_df.to_csv(FAILURES_PATH, index=False)
        print(f"Failed: {len(failures)} (logged to {FAILURES_PATH})")
        print(fail_df["reason"].value_counts().to_string())
    else:
        print("Failed: 0")
    print(f"Saved {OUT_PATH}")

    if rows:
        print("\nMAJORITY UNDERTONE DISTRIBUTION (centre 42.4)")
        print("-" * 60)
        print(df["majority_undertone"].value_counts().to_string())

        print("\nTIE RATE")
        print("-" * 60)
        tie_rate = 100 * df["was_tied"].mean()
        print(f"{int(df['was_tied'].sum())} / {len(df)} images tied ({tie_rate:.2f}%)")

        incomplete = int((df["n_regions_present"] < 5).sum())
        print(f"\nImages with <5 measured regions: {incomplete} / {len(df)}")

        print_comparison(df)


if __name__ == "__main__":
    run()
