"""
Phase 9 -- Full-Dataset Undertone Descriptor (batch run)

Computes the Majority Undertone Label (and the 5 per-region hue angles and
labels that feed it) across the full landmarked dataset, using the real
masks in label_maps/ and the evidenced original_rgb CIELAB source decided
in Phase 8.2.

Only the full_face configuration is processed per image -- it already
contains all 5 individual regions' hue/label as part of its own
computation, so separately running the 5 single-region configs would just
recompute numerically identical hue values from the same underlying
patches.

This is the actual data behind the manuscript's Appendix 5 ("Undertone
outputs generated by HueView... are reported descriptively in Appendix 5
only") -- not a QA sample.

Input:
    data/processed/landmarks_index.csv
    data/processed/label_maps/<filename, .png>        -- from 7.4
    data/processed/faces_ssr/<filename>                -- from 7.2
    (original pre-SSR crop located via path_resolver, matching the frozen
     original_rgb CIELAB source decision from Phase 8.2)

Output:
    data/processed/phase9_undertone.csv -- one row per image:
        filename, <region>_hue_deg, <region>_undertone (x5),
        majority_undertone, was_tied, n_regions_present
    data/processed/phase9_failures.csv  -- filename, reason (only if any)
"""

# BLAS thread-limiting before numpy/skimage/cv2 import anywhere -- same fix
# as qa_cielab_source_compare.py; build_cielab_vector's skimage.color.rgb2lab
# call is BLAS-backed, and 12 worker processes each doing that repeatedly
# causes OpenBLAS thread oversubscription without this.
import os

os.environ.setdefault("OMP_NUM_THREADS", "1")
os.environ.setdefault("OPENBLAS_NUM_THREADS", "1")
os.environ.setdefault("MKL_NUM_THREADS", "1")
os.environ.setdefault("NUMEXPR_NUM_THREADS", "1")
os.environ.setdefault("VECLIB_MAXIMUM_THREADS", "1")

import sys
from pathlib import Path
from multiprocessing import Pool, cpu_count

import cv2
import numpy as np
import pandas as pd
from tqdm import tqdm

# ------------------------------------------------------------ project root --


def find_project_root(start: Path, marker: str = "data") -> Path:
    for candidate in [start] + list(start.parents):
        if (candidate / marker).is_dir():
            return candidate
    return start


PROJECT_ROOT = find_project_root(Path(__file__).resolve().parent)
sys.path.insert(0, str(PROJECT_ROOT / "src"))

from ml_pipeline.src.baseline.path_resolver import resolve_image_path  # noqa: E402
from ml_pipeline.src.hueview.regions import decode_label_map, REGION_ORDER  # noqa: E402
from ml_pipeline.src.hueview.region_selector import RegionalConfigurationSelector, FULL_FACE  # noqa: E402
from ml_pipeline.src.hueview.cielab_features import build_cielab_vector  # noqa: E402
from ml_pipeline.src.hueview.undertone import compute_undertone_descriptor  # noqa: E402

# ---------------------------------------------------------------- config --

INDEX_PATH = PROJECT_ROOT / "data" / "processed" / "landmarks_index.csv"
LABEL_MAPS_ROOT = PROJECT_ROOT / "data" / "processed" / "label_maps"
SSR_ROOT = PROJECT_ROOT / "data" / "processed" / "faces_ssr"
OUT_PATH = PROJECT_ROOT / "data" / "processed" / "phase9_undertone.csv"
FAILURES_PATH = PROJECT_ROOT / "data" / "processed" / "phase9_failures.csv"

LIMIT = None  # e.g. 50 to sanity-check before the full run

# --------------------------------------------------------------- worker --


def process_one(filename: str):
    label_path = LABEL_MAPS_ROOT / Path(filename).with_suffix(".png")
    ssr_path = SSR_ROOT / filename

    label = cv2.imread(str(label_path), cv2.IMREAD_UNCHANGED)
    ssr_bgr = cv2.imread(str(ssr_path))
    if label is None or ssr_bgr is None:
        return (filename, None, "label_map_or_ssr_missing")

    ssr_rgb = cv2.cvtColor(ssr_bgr, cv2.COLOR_BGR2RGB)
    patches = decode_label_map(label, ssr_rgb)

    orig_path, _, _ = resolve_image_path(filename)
    if orig_path is None:
        return (filename, None, "original_not_found")
    orig_bgr = cv2.imread(str(orig_path))
    if orig_bgr is None:
        return (filename, None, "original_unreadable")
    orig_rgb = cv2.cvtColor(orig_bgr, cv2.COLOR_BGR2RGB)

    selector = RegionalConfigurationSelector(configurations=(FULL_FACE,))
    outputs = list(selector.route(patches, image_id=filename))
    if not outputs:
        return (filename, None, "full_face_unusable")

    cfg = outputs[0]
    cielab_vec = build_cielab_vector(cfg, original_rgb=orig_rgb)
    result = compute_undertone_descriptor(cfg, cielab_vec)

    row = {"filename": filename}
    for name in REGION_ORDER:
        region_info = result["regions"].get(name)
        row[f"{name}_hue_deg"] = round(region_info["hue_deg"], 2) if region_info else None
        row[f"{name}_undertone"] = region_info["undertone"] if region_info else None
    row["majority_undertone"] = result["majority_undertone"]
    row["was_tied"] = result["was_tied"]
    row["n_regions_present"] = len(result["regions"])

    return (filename, row, None)


# --------------------------------------------------------------- main --


def run():
    print(f"Project root: {PROJECT_ROOT}")

    if not INDEX_PATH.is_file():
        raise SystemExit(f"ERROR: {INDEX_PATH} not found.")

    index_df = pd.read_csv(INDEX_PATH)
    filenames = index_df["filename"].tolist()
    print(f"{INDEX_PATH.name}: {len(filenames)} images")

    if LIMIT:
        filenames = filenames[:LIMIT]
        print(f"LIMIT set -- only processing {len(filenames)} images")

    print(f"Total: {len(filenames)} images, {cpu_count()} workers")

    rows = []
    failures = []

    with Pool(processes=cpu_count()) as pool:
        for filename, row, error in tqdm(pool.imap_unordered(process_one, filenames), total=len(filenames)):
            if error is not None:
                failures.append({"filename": filename, "reason": error})
            else:
                rows.append(row)

    df = pd.DataFrame(rows)
    df.to_csv(OUT_PATH, index=False)

    print(f"\nProcessed {len(rows)} / {len(filenames)} images successfully")
    if failures:
        pd.DataFrame(failures).to_csv(FAILURES_PATH, index=False)
        print(f"Failed: {len(failures)} (logged to {FAILURES_PATH})")
    else:
        print("Failed: 0")
    print(f"Saved {OUT_PATH}")

    if rows:
        print("\nMAJORITY UNDERTONE DISTRIBUTION")
        print("-" * 60)
        print(df["majority_undertone"].value_counts().to_string())

        print("\nTIE RATE")
        print("-" * 60)
        tie_rate = 100 * df["was_tied"].mean()
        print(f"{int(df['was_tied'].sum())} / {len(df)} images tied ({tie_rate:.2f}%)")

        incomplete = int((df["n_regions_present"] < 5).sum())
        print(f"\nImages with <5 regions present: {incomplete} / {len(df)}")


if __name__ == "__main__":
    run()
