"""
Phase 7.5 -- Full-Dataset Regional Configuration Routing (batch run)

RegionalConfigurationSelector is a generator meant to be called once per
image inside the Phase 8 training loop, per its own docstring -- it holds
no learned parameters and produces no features. This script exists to
produce the artifact its docstring calls for regardless:
results/phase7_routing_log.csv, "the evidence for two things the panel is
likely to ask about: how many regions needed the relaxed or fallback
filter, and how many images contributed fewer than five regions to their
Full Face vector" -- across the REAL full dataset, not a QA sample.

Masks and per-region images are reconstructed from the compact label maps
written by run_phase7_4_batch.py via regions.decode_label_map(), using the
already-generated SSR images (converted to RGB, matching the
convention the patches were originally built with).

Inputs:
    ml_pipeline/data/processed/landmarks_index.csv
    ml_pipeline/data/processed/label_maps/<filename, .png>
    ml_pipeline/data/processed/images_ssr/<filename>
    ml_pipeline/data/processed/phase7_4_full_coverage_stats.csv

Outputs:
    results/phase7_routing_log.csv
    ml_pipeline/data/processed/phase7_5_failures.csv
"""

import os
import re
import sys
from pathlib import Path
from multiprocessing import Pool, cpu_count

import cv2
import numpy as np
import pandas as pd
from tqdm import tqdm

# ------------------------------------------------------------ project root --


def find_project_root(start: Path, marker: str = "ml_pipeline") -> Path:
    """Walk upward from `start` until a directory containing `marker` is found."""
    for candidate in [start] + list(start.parents):
        if (candidate / marker).is_dir():
            return candidate
        if candidate.name == marker:
            return candidate.parent
    return start


PROJECT_ROOT = find_project_root(Path(__file__).resolve().parent)

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from ml_pipeline.src.hueview.regions import decode_label_map, REGION_ORDER  # noqa: E402
from ml_pipeline.src.hueview.region_selector import RegionalConfigurationSelector  # noqa: E402

# ---------------------------------------------------------------- config --

DATA_PROCESSED = PROJECT_ROOT / "ml_pipeline" / "data" / "processed"
INDEX_PATH = DATA_PROCESSED / "landmarks_index.csv"
LABEL_MAPS_ROOT = DATA_PROCESSED / "label_maps"
SSR_ROOT = DATA_PROCESSED / "images_ssr"
STATS_PATH = DATA_PROCESSED / "phase7_4_full_coverage_stats.csv"

OUT_PATH = PROJECT_ROOT / "results" / "phase7_routing_log.csv"
FAILURES_PATH = DATA_PROCESSED / "phase7_5_failures.csv"

LIMIT = None  # Process all entries from landmarks_index.csv

# ----------------------------------------------------------- status lookup --


def load_status_lookup() -> dict:
    """{(filename, region): true_status} from the real Phase 7.4 run."""
    if not STATS_PATH.is_file():
        return {}
    df = pd.read_csv(STATS_PATH)
    return {(row.filename, row.region): row.status for row in df.itertuples()}


STATUS_LOOKUP = load_status_lookup()

# ---------------------------------------------------------- path resolvers --


def get_path_variants(file_str: str) -> list[str]:
    """Generates clean filename variants and swaps extensions (.png <-> .bmp <-> .jpg)."""
    clean_str = re.sub(r"\s*\(\d+\)", "", file_str)
    variants = [file_str, clean_str]

    extended_variants = []
    for var in variants:
        p = Path(var)
        extended_variants.append(var)
        for ext in [".bmp", ".jpg", ".png", ".jpeg"]:
            if p.suffix.lower() != ext:
                extended_variants.append(str(p.with_suffix(ext)))

    return list(dict.fromkeys(extended_variants))


def resolve_ssr_path(filename: str) -> Path | None:
    """Locates the SSR image across cohort directories and extension variants."""
    str_file = str(filename).replace("\\", "/")
    if "images/" in str_file:
        str_file = str_file.split("images/")[-1]

    variants = get_path_variants(str_file)

    # Direct check under SSR_ROOT
    for var in variants:
        cand = SSR_ROOT / var
        if cand.is_file():
            return cand

    # Priority cohort directories check
    cohorts = ["processed", "v5_processed", "c1_processed", "c2_processed"]
    for cohort in cohorts:
        for var in variants:
            cand = SSR_ROOT / cohort / var
            if cand.is_file():
                return cand

    # Fallback recursive search by filename
    bare_names = list(set(Path(v).name.lower() for v in variants))
    for bare_name in bare_names:
        matched = list(SSR_ROOT.rglob(bare_name))
        if matched and matched[0].is_file():
            return matched[0]

    return None


def resolve_label_map_path(filename: str) -> Path | None:
    """Locates the encoded label map PNG generated by Phase 7.4."""
    str_file = str(filename).replace("\\", "/")
    if "images/" in str_file:
        str_file = str_file.split("images/")[-1]

    variants = get_path_variants(str_file)

    for var in variants:
        png_var = str(Path(var).with_suffix(".png"))
        cand = LABEL_MAPS_ROOT / png_var
        if cand.is_file():
            return cand

    # Fallback search by bare filename in LABEL_MAPS_ROOT
    bare_names = list(set(Path(v).with_suffix(".png").name.lower() for v in variants))
    for bare_name in bare_names:
        matched = list(LABEL_MAPS_ROOT.rglob(bare_name))
        if matched and matched[0].is_file():
            return matched[0]

    return None


# --------------------------------------------------------------- worker --


def process_one(filename: str):
    label_path = resolve_label_map_path(filename)
    ssr_path = resolve_ssr_path(filename)

    if label_path is None or ssr_path is None:
        return (filename, None, "label_map_or_ssr_missing")

    label = cv2.imread(str(label_path), cv2.IMREAD_UNCHANGED)
    ssr_bgr = cv2.imread(str(ssr_path))

    if label is None or ssr_bgr is None:
        return (filename, None, "label_map_or_ssr_unreadable")

    ssr_rgb = cv2.cvtColor(ssr_bgr, cv2.COLOR_BGR2RGB)
    patches = decode_label_map(label, ssr_rgb)

    # Restore the true status -- decode_label_map only knows ok/empty.
    for region, patch in patches.items():
        true_status = STATUS_LOOKUP.get((filename, region))
        if true_status is not None:
            patch.status = true_status

    selector = RegionalConfigurationSelector()
    outputs = list(selector.route(patches, image_id=filename))
    row = selector.routing_record(filename, outputs)
    return (filename, row, None)


# --------------------------------------------------------------- main --


def run():
    print(f"Project root: {PROJECT_ROOT}")

    if not INDEX_PATH.is_file():
        raise SystemExit(f"ERROR: {INDEX_PATH} not found -- run landmark_extraction.py (7.1) first.")
    if not STATS_PATH.is_file():
        raise SystemExit(f"ERROR: {STATS_PATH} not found -- run run_phase7_4_batch.py first.")

    index_df = pd.read_csv(INDEX_PATH)
    filenames = index_df["filename"].tolist()
    print(f"{INDEX_PATH.name}: {len(filenames)} images")

    if LIMIT:
        filenames = filenames[:LIMIT]
        print(f"LIMIT set -- only processing {len(filenames)} images")

    rows = []
    failures = []
    with Pool(processes=cpu_count()) as pool:
        for filename, row, error in tqdm(
            pool.imap_unordered(process_one, filenames),
            total=len(filenames),
            desc="Phase 7.5",
        ):
            if error is not None:
                failures.append({"filename": filename, "reason": error})
            else:
                rows.append(row)

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    df = pd.DataFrame(rows)
    df.to_csv(OUT_PATH, index=False)

    print(f"\nProcessed {len(rows)} / {len(filenames)} images successfully")
    if failures:
        pd.DataFrame(failures).to_csv(FAILURES_PATH, index=False)
        print(f"Failed: {len(failures)} (logged to {FAILURES_PATH})")
    else:
        print("Failed: 0")
    print(f"Saved routing log to {OUT_PATH}")

    if rows:
        print("\nFULL FACE COMPLETENESS")
        print("-" * 60)
        for k in range(5, -1, -1):
            n = int((df["full_face_regions_present"] == k).sum())
            if n:
                tag = "all 5 regions present" if k == 5 else f"exactly {k} region(s) present"
                print(f"  {n} images with {tag}")

        print("\nCONFIG STATUS COUNTS")
        print("-" * 60)
        for config in list(REGION_ORDER) + ["full_face"]:
            col = f"{config}_status"
            if col in df.columns:
                print(f"{config:12s}: {df[col].value_counts().to_dict()}")


if __name__ == "__main__":
    run()