"""
Phase 9 -- Full-Dataset Undertone Descriptor (batch run)

Computes the Majority Undertone Label (and the 5 per-region hue angles and
labels that feed it) across the full landmarked dataset, using the real
masks in label_maps/.

CIELAB SOURCE -- follows the manuscript:
    Stage 6 "utilizes the CIELAB Feature Vector produced in Stage 5", and
    Stage 5 converts "the per-region skin samples produced by the SSR stage".
    So the undertone is computed from the SSR image (CIELAB_SOURCE = "ssr").

    An earlier version used the original (pre-SSR) crop instead, based on the
    Phase 8.2 source comparison (qa_cielab_source_compare.py) run when SSR
    used sigma = 80, which flattened a*/b*. SSR now uses sigma = 30.
    CIELAB_SOURCE = "original" is kept as a DIAGNOSTIC only: it writes to a
    separate CSV so the two can be compared for the adviser, and it must not
    be reported as HueView's undertone unless the manuscript's Stage 5/6 are
    changed to say so.

Only the full_face configuration is processed per image -- it already
contains all 5 individual regions' hue/label as part of its own computation,
so separately running the 5 single-region configs would just recompute
numerically identical hue values from the same underlying patches. Regions
with no usable skin pixels are excluded from the vote (undertone.py).

This is the actual data behind the manuscript's Appendix 5 ("Undertone
outputs generated by HueView... are reported descriptively in Appendix 5
only") -- not a QA sample.

Input:
    data/processed/landmarks_index.csv
    data/processed/label_maps/<filename, .png>        -- from 7.4
    data/processed/faces_ssr/<filename>                -- from 7.2 (sigma = 30)
    (original pre-SSR crop via path_resolver -- diagnostic mode only)

Output:
    data/processed/phase9_undertone.csv -- one row per image:
        filename, <region>_hue_deg, <region>_undertone (x5),
        majority_undertone, was_tied, n_regions_present
        (n_regions_present = regions that were actually measured and voted)
    data/processed/phase9_failures.csv  -- filename, reason (only if any)
    Diagnostic mode writes phase9_undertone_original_diagnostic.csv /
    phase9_failures_original_diagnostic.csv instead.
"""

# BLAS thread-limiting before numpy/skimage/cv2 import anywhere -- same fix
# as qa_cielab_source_compare.py; build_cielab_vector's skimage.color.rgb2lab
# call is BLAS-backed, and 12 worker processes each doing that repeatedly
# causes OpenBLAS thread oversubscription without this.
import os

os.environ.setdefault("OMP_NUM_THREADS", "1")
os.environ.setdefault("OPENBLAS_NUM_THREADS", "1")
os.environ.setdefault("MKL_NUM_THREADS", "1")
os.environ.setdefault("NUMEXPR_NUM_THREADS", "1")
os.environ.setdefault("VECLIB_MAXIMUM_THREADS", "1")

import sys
from pathlib import Path
from multiprocessing import Pool, cpu_count

import cv2
import numpy as np
import pandas as pd
from tqdm import tqdm

# ------------------------------------------------------------ project root --


def find_project_root(start: Path, marker: str = "data") -> Path:
    for candidate in [start] + list(start.parents):
        if (candidate / marker).is_dir():
            return candidate
    return start


PROJECT_ROOT = find_project_root(Path(__file__).resolve().parent)
sys.path.insert(0, str(PROJECT_ROOT / "src"))

from ml_pipeline.src.baseline.path_resolver import resolve_image_path  # noqa: E402
from ml_pipeline.src.hueview.regions import decode_label_map, REGION_ORDER  # noqa: E402
from ml_pipeline.src.hueview.region_selector import RegionalConfigurationSelector, FULL_FACE  # noqa: E402
from ml_pipeline.src.hueview.cielab_features import build_cielab_vector  # noqa: E402
from ml_pipeline.src.hueview.undertone import compute_undertone_descriptor  # noqa: E402

# ---------------------------------------------------------------- config --

INDEX_PATH = PROJECT_ROOT / "data" / "processed" / "landmarks_index.csv"
LABEL_MAPS_ROOT = PROJECT_ROOT / "data" / "processed" / "label_maps"
SSR_ROOT = PROJECT_ROOT / "data" / "processed" / "faces_ssr"
OUT_PATH = PROJECT_ROOT / "data" / "processed" / "phase9_undertone.csv"
FAILURES_PATH = PROJECT_ROOT / "data" / "processed" / "phase9_failures.csv"

LIMIT = None  # e.g. 50 to sanity-check before the full run

# "ssr"      -- manuscript (Stage 6 -> Stage 5 -> SSR image). Use this.
# "original" -- pre-SSR colour, DIAGNOSTIC only, written to separate files.
CIELAB_SOURCE = "ssr"

if CIELAB_SOURCE not in ("ssr", "original"):
    raise SystemExit(f"CIELAB_SOURCE must be 'ssr' or 'original', got {CIELAB_SOURCE!r}")
if CIELAB_SOURCE == "original":
    OUT_PATH = OUT_PATH.with_name("phase9_undertone_original_diagnostic.csv")
    FAILURES_PATH = FAILURES_PATH.with_name("phase9_failures_original_diagnostic.csv")

# --------------------------------------------------------------- worker --


def process_one(filename: str):
    label_path = LABEL_MAPS_ROOT / Path(filename).with_suffix(".png")
    ssr_path = SSR_ROOT / filename

    label = cv2.imread(str(label_path), cv2.IMREAD_UNCHANGED)
    ssr_bgr = cv2.imread(str(ssr_path))
    if label is None or ssr_bgr is None:
        return (filename, None, "label_map_or_ssr_missing")

    ssr_rgb = cv2.cvtColor(ssr_bgr, cv2.COLOR_BGR2RGB)
    patches = decode_label_map(label, ssr_rgb)

    # The original (pre-SSR) crop is only needed for the diagnostic mode.
    orig_rgb = None
    if CIELAB_SOURCE == "original":
        orig_path, _, _ = resolve_image_path(filename)
        if orig_path is None:
            return (filename, None, "original_not_found")
        orig_bgr = cv2.imread(str(orig_path))
        if orig_bgr is None:
            return (filename, None, "original_unreadable")
        orig_rgb = cv2.cvtColor(orig_bgr, cv2.COLOR_BGR2RGB)

    selector = RegionalConfigurationSelector(configurations=(FULL_FACE,))
    outputs = list(selector.route(patches, image_id=filename))
    if not outputs:
        return (filename, None, "full_face_unusable")

    cfg = outputs[0]
    cielab_vec = build_cielab_vector(cfg, original_rgb=orig_rgb)
    result = compute_undertone_descriptor(cfg, cielab_vec)
    if result is None:
        # No region had usable skin pixels -- nothing was measured.
        return (filename, None, "no_measured_regions")

    row = {"filename": filename}
    for name in REGION_ORDER:
        region_info = result["regions"].get(name)
        row[f"{name}_hue_deg"] = round(region_info["hue_deg"], 2) if region_info else None
        row[f"{name}_undertone"] = region_info["undertone"] if region_info else None
    row["majority_undertone"] = result["majority_undertone"]
    row["was_tied"] = result["was_tied"]
    row["n_regions_present"] = result["n_regions_voted"]  # measured regions only

    return (filename, row, None)


# --------------------------------------------------------------- main --


def run():
    print(f"Project root: {PROJECT_ROOT}")
    print(f"CIELAB source: {CIELAB_SOURCE}"
          + ("  (manuscript)" if CIELAB_SOURCE == "ssr" else "  (DIAGNOSTIC -- not the reported result)"))

    if not INDEX_PATH.is_file():
        raise SystemExit(f"ERROR: {INDEX_PATH} not found.")

    index_df = pd.read_csv(INDEX_PATH)
    filenames = index_df["filename"].tolist()
    print(f"{INDEX_PATH.name}: {len(filenames)} images")

    if LIMIT:
        filenames = filenames[:LIMIT]
        print(f"LIMIT set -- only processing {len(filenames)} images")

    print(f"Total: {len(filenames)} images, {cpu_count()} workers")

    rows = []
    failures = []

    with Pool(processes=cpu_count()) as pool:
        for filename, row, error in tqdm(pool.imap_unordered(process_one, filenames), total=len(filenames)):
            if error is not None:
                failures.append({"filename": filename, "reason": error})
            else:
                rows.append(row)

    df = pd.DataFrame(rows)
    df.to_csv(OUT_PATH, index=False)

    print(f"\nProcessed {len(rows)} / {len(filenames)} images successfully")
    if failures:
        fail_df = pd.DataFrame(failures)
        fail_df.to_csv(FAILURES_PATH, index=False)
        print(f"Failed: {len(failures)} (logged to {FAILURES_PATH})")
        print(fail_df["reason"].value_counts().to_string())
    else:
        print("Failed: 0")
    print(f"Saved {OUT_PATH}")

    if rows:
        print("\nMAJORITY UNDERTONE DISTRIBUTION")
        print("-" * 60)
        print(df["majority_undertone"].value_counts().to_string())

        print("\nTIE RATE")
        print("-" * 60)
        tie_rate = 100 * df["was_tied"].mean()
        print(f"{int(df['was_tied'].sum())} / {len(df)} images tied ({tie_rate:.2f}%)")

        incomplete = int((df["n_regions_present"] < 5).sum())
        print(f"\nImages with <5 measured regions: {incomplete} / {len(df)}")


if __name__ == "__main__":
    run()
